apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs_wordpress
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /k8s_demo
    server: 192.168.1.40
